#!/usr/bin/env/python
import sys
sys.path.append('/usr/local/lib/python2.7/site-packages')
import paramiko

HOST = '10.0.10.115'
PORT = 22
ADDR = (HOST, PORT)
remote_tester = paramiko.SSHClient()
remote_tester.connect(hostname = '10.0.10.115', username = 'root')
stdin,stdout,stderr = remote_tester.exec_command('ifconfig')
print stdout.readlines()
remote_tester.close()
